[general]
import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.95
decorations = "None"
dimensions = { columns = 160, lines = 50 }

[font]
normal = { family = "Hack Nerd Font Mono" }
italic = { family = "Adwaita Mono" }
